@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.kidsbank.controller.HomeController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_827112919 { 
   	label=kidsbank
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   Main14625802[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Main</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ changeView(fxmlFile: String, title: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ opnNewView(fxmlFile: String, title: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ start(stage: Stage)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

subgraph cluster_1371265191 { 
   	label=util
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ButtonHandle703749882[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ButtonHandle</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ labelClick(label: Label)</TD></TR>
<TR><TD ALIGN="LEFT" >+ mouseEntered(button: Button)</TD></TR>
<TR><TD ALIGN="LEFT" >+ mouseExited(button: Button)</TD></TR>
<TR><TD ALIGN="LEFT" >+ unlinkButtonAction(button: Button, userName: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CSVFileHandler703749882[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CSVFileHandler</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ addDataToCSV(filePath: String, newData: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ deleteSingleLine(filePath: String, id: String, idColumn: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCSVMultipleValue(filePath: String, columnValue: String, column1: int, column2: int): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCSVMultipleValue2(filePath: String, columnValue1: String, column1: int, columnValue2: String, column2: int, column3: int): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCSVMultipleValue3(filePath: String, columnValue1: String, column1: int, columnValue21: String, columnValue22: String, columnValue23: String, column2: int, months: int, column3: int, column4: int): List&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCSVRowCount(filePath: String): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCSVSingleValue(filePath: String, columnValue: String, column1: int, column2: int): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCSVSingleValue2(filePath: String, columnValue1: String, column1: int, columnValue2: String, column2: int, column3: int): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getGiftList(filePath: String, data1: String, column1: int, data2: String, column2: int): List&lt;GiftInfo&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getLastRowColumnValue(filePath: String, colNum: int): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getTasksList(filePath: String, data1: String, column1: int, data2: String, column2: int): List&lt;TaskInfo&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ isLastLineEmpty(filePath: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateSingleDataToCSV(filePath: String, newData: String, column: int, id: String, idColumn: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateSingleDataToCSV2(filePath: String, newData: String, column: int, column1Value: String, column1: int, column2Value: String, column2: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CalculateBalance703749882[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CalculateBalance</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getBalance(csvFile: String, userId: String): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ getBalanceForOneMonthAgo(csvFile: String, userId: String): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ getExpense(csvFile: String, userId: String): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ getFixedDeposit(csvFile: String, userId: String): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ getIncome(csvFile: String, userId: String): double</TD></TR>
<TR><TD ALIGN="LEFT" >+ getInterest(csvFile: String, userId: String): double</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

GetTime703749882[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)GetTime</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ compareWithCurrentTime(time: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ compareWithSpecificTime(specificTime: String, months: int): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ convertTimeFormat(oldFormatDate: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getFutureTime(year: String): String</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PageLoader703749882[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PageLoader</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   view: Pane [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getPage(fxmlFile: String): Pane</TD></TR>
<TR><TD ALIGN="LEFT" >+ gotoPage(viewName: String, button: Button)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_43613313 { 
   	label=controller
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   HomeController66631828[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)HomeController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   balanceLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   changeButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   childDataPrompt: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   expenseLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   goalComment: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   goalEditButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   goalLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   goalPercentageLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gotoDepositPageButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gotoEarnPageButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   gotoGiftPageButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   headerPane: Pane [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   incomeLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   increaseLabel: Label [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   progressBar: ProgressBar [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   refreshButton: Button [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- changeButtonAction()</TD></TR>
<TR><TD ALIGN="LEFT" >+ changeMouseEntered()</TD></TR>
<TR><TD ALIGN="LEFT" >+ changeMouseExited()</TD></TR>
<TR><TD ALIGN="LEFT" >+ depositMouseEntered()</TD></TR>
<TR><TD ALIGN="LEFT" >+ depositMouseExited()</TD></TR>
<TR><TD ALIGN="LEFT" >+ earnMouseEntered()</TD></TR>
<TR><TD ALIGN="LEFT" >+ earnMouseExited()</TD></TR>
<TR><TD ALIGN="LEFT" >+ editorMouseEntered()</TD></TR>
<TR><TD ALIGN="LEFT" >+ editorMouseExited()</TD></TR>
<TR><TD ALIGN="LEFT" >+ giftMouseEntered()</TD></TR>
<TR><TD ALIGN="LEFT" >+ giftMouseExited()</TD></TR>
<TR><TD ALIGN="LEFT" >+ gotoAccount()</TD></TR>
<TR><TD ALIGN="LEFT" >+ gotoDepositPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ gotoEarnPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ gotoGiftPage()</TD></TR>
<TR><TD ALIGN="LEFT" >+ gotoGoalEditor()</TD></TR>
<TR><TD ALIGN="LEFT" >- initialize()</TD></TR>
<TR><TD ALIGN="LEFT" >+ refreshButtonAction()</TD></TR>
<TR><TD ALIGN="LEFT" >+ refreshMouseEntered()</TD></TR>
<TR><TD ALIGN="LEFT" >+ refreshMouseExited()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
ButtonHandle703749882 -> CSVFileHandler703749882[label="unlinkButtonAction() -> updateSingleDataToCSV()"];
ButtonHandle703749882 -> PageLoader703749882[label="unlinkButtonAction() -> gotoPage()"];
CSVFileHandler703749882 -> GetTime703749882[label="getCSVMultipleValue3() -> compareWithSpecificTime()"];
CSVFileHandler703749882 -> PageLoader703749882[label="getTasksList() -> gotoPage()"];
HomeController66631828 -> Main14625802[label="gotoGoalEditor() -> opnNewView()"];
    
}
@enduml